### ISSUE TITLE
Withdraw Wallet Fragment - QR Code Scanner: Doesn't return to Withdraw Fragment after back button is pressed - Camera release problem

### ISSUE THREAD

**Issue by tobywoerthle** [DanielPollithy/flashwifi#1]
```
E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                     java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                         at android.hardware.Camera.setHasPreviewCallback(Native Method)
                                                                         at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:820)
                                                                         at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169)
                                                                         at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1129)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by tobywoerthle** [comment]
May be library bug: https://github.com/dm77/barcodescanner/issues/294

Odd thing is this doesn't happen in the IOTA wallet (iotaledger/android-wallet-app)
